/* eslint-disable require-yield, eqeqeq */

import {
  Stage as StageBase,
  Trigger,
  Watcher,
  Costume,
  Color,
  Sound
} from "https://unpkg.com/leopard@^1/dist/index.esm.js";

export default class Stage extends StageBase {
  constructor(...args) {
    super(...args);

    this.costumes = [
      new Costume("backdrop1", "./Stage/costumes/backdrop1.png", {
        x: 480,
        y: 360
      })
    ];

    this.sounds = [
      new Sound("sfx_swooshing", "./Stage/sounds/sfx_swooshing.wav")
    ];

    this.triggers = [
      new Trigger(
        Trigger.BROADCAST,
        { name: "game.mute" },
        this.whenIReceiveGameMute
      ),
      new Trigger(Trigger.GREEN_FLAG, this.whenGreenFlagClicked),
      new Trigger(Trigger.BROADCAST, { name: "Menu" }, this.whenIReceiveMenu),
      new Trigger(Trigger.BROADCAST, { name: "Menu" }, this.whenIReceiveMenu2),
      new Trigger(Trigger.BROADCAST, { name: "Start" }, this.whenIReceiveStart),
      new Trigger(
        Trigger.BROADCAST,
        { name: "show.rate" },
        this.whenIReceiveShowRate
      ),
      new Trigger(
        Trigger.BROADCAST,
        { name: "hide.rate" },
        this.whenIReceiveHideRate
      ),
      new Trigger(Trigger.BROADCAST, { name: "Tap" }, this.whenIReceiveTap),
      new Trigger(
        Trigger.BROADCAST,
        { name: "Game Over" },
        this.whenIReceiveGameOver
      ),
      new Trigger(
        Trigger.BROADCAST,
        { name: "show.highscores" },
        this.whenIReceiveShowHighscores
      ),
      new Trigger(
        Trigger.BROADCAST,
        { name: "hide.highscores" },
        this.whenIReceiveHideHighscores
      ),
      new Trigger(
        Trigger.BROADCAST,
        { name: "show.settings" },
        this.whenIReceiveShowSettings
      ),
      new Trigger(
        Trigger.BROADCAST,
        { name: "hide.settings" },
        this.whenIReceiveHideSettings
      ),
      new Trigger(
        Trigger.BROADCAST,
        { name: "Game Over" },
        this.whenIReceiveGameOver2
      )
    ];

    this.vars.gameScrollx = -3.5;
    this.vars.userScore = 0;
    this.vars.birdGravity = 0;
    this.vars.birdFlap = "ture";
    this.vars.birdDie = "false";
    this.vars.birdPlay = "false";
    this.vars.userEarnmedal = 0;
    this.vars.scoreClones = 1;
    this.vars.userSethighscore = "false";
    this.vars.gameMute = "false";
    this.vars.birdCostume = 3;
    this.vars.pipeNew = "true";
    this.vars.gamePause = "false";
    this.vars.GamesPlayed = 127798;
    this.vars.LatestScore = 1;
    this.vars.userHighscore = 0;
    this.vars.gameMode = "normal";
    this.vars.userPoints = 0;
    this.vars.flapSpeed = 0.1;
    this.vars.gameTime = "day";
    this.vars.birdCostumeRandom = "true";
    this.vars.gameTimeRandom = "true";
    this.vars.ListUsernamesHighscore = null;
    this.vars.encodeUsername = "false";
    this.vars.moderators = [
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer",
      "HyperPixel",
      "theONLYsiemer"
    ];
    this.vars.HighScoreList = [
      "JAEWON0907 - 64",
      "IVANISAAC - 57",
      "FIZZYPOPPIPPOP - 41",
      "MATHICIAN - 28",
      "PEREZJU2024 - 26",
      "THEFIERYHAZE - 23",
      "IDECRUZ2019 - 23",
      "ICECREAMKITTYZ - 20",
      "TOMATOEEEEEEEEEEE - 17",
      "RETRO-GAMES - 17",
      "RYANBACK - 16",
      "ORUIZ1234567890 - 16",
      "WENDOVER03 - 15",
      "INOAHIPLAY - 15",
      "JIANGM1 - 15",
      "BESTGAMES5 - 14",
      "DRAGONPRODUCTION - 14",
      "CS449851 - 14",
      "DABAWSESOPHIA - 14",
      "CEGORDON - 14",
      "BLOBFISHKING101 - 13",
      "WOLF-ALEXI - 14",
      "LSCGYKM3 - 13",
      "TOASTY_BOY - 13",
      "HEATER123 - 13",
      "3GGEN - 13",
      "JOSEEE_530 - 13",
      "TON999 - 12",
      "BOBBOB41 - 12",
      "55WOMBAT55 - 12",
      "PANDACAT2 - 12",
      "LSCBB3 - 12",
      "890H - 12",
      "NEXUS797 - 12",
      "HIKARUARAI - 12",
      "GEV07 - 12",
      "33O - 12",
      "DIAMONDOPOLIS - 11",
      "MNSRUBIKS - 11",
      "ANIME_FAN15 - 11",
      "KOZYBEE - 11",
      "TERRELLG05 - 11",
      "CODERKIDSTX - 11",
      "NYUSZIKAR - 11",
      "PORKCHAP - 11",
      "I_LOVE_PUSHEEN - 10",
      "ELCONEJITOCOOL442 - 11",
      "GARYDOS - 10",
      "MKIMM2K - 10",
      "BOOKSLOVER - 10",
      "CONMOM456 - 10",
      "SQUEAKYCLEANSTUDIOS - 10",
      "TYLER0926 - 10",
      "HMONGCOOLBOI530 - 10",
      "PATRICKWIJONO - 10",
      "DCOLEMAN0915 - 9",
      "THAISON1 - 9",
      "TRUEGAMER95 - 9",
      "GOOGLE_NETWORK - 9",
      "CPTURTLES - 9",
      "PACK48 - 9",
      "ALEC2121 - 9",
      "CPETERSON4917 - 9",
      "FUNKMAN251SCRATCH - 9",
      "NIMBLEMATIONS - 9",
      "DIEGOB10 - 9",
      "TOM20051124 - 9",
      "RAEFWORKS_ANIMATIONS - 9",
      "BOTTLEFLIPPER789 - 9",
      "SERPERIOR1700 - 9",
      "X126 - 9",
      "FARZATTACK - 9",
      "DANIELCODING - 9",
      "VENOM2005 - 8",
      "LINKKI - 8",
      "PETPAWS16 - 8",
      "APPLEMACBOOKPRO2015 - 8",
      "NILE1 - 8",
      "ALEXANDERRUBINO05 - 8",
      "MSUMANNING - 8",
      "SCORPIOTHEDESTROYER - 8",
      "4NGUYEN - 8",
      "GC123456 - 8",
      "TRUES4SAMI - 8",
      "PSTUDEBAKER20 - 8",
      "ALEXSHAKES - 8",
      "PROGRAMINGMASTER17 - 8",
      "JOELBON9 - 8",
      "FIREBOIT - 8",
      "CS546448 - 8",
      "MUTTPUG101 - 8",
      "CBLAKELY - 7",
      "APEKATTEN - 7",
      "REDDEY13 - 7",
      "21AUGSH - 7",
      "CS455898 - 7",
      "COOKIECAMPO23 - 7",
      "23DANIELSELOGY - 7",
      "COOLMARIO4 - 7",
      "MIKSUK28 - 7"
    ];

    this.watchers.HighScoreList = new Watcher({
      label: "☁ High Score List",
      style: "normal",
      visible: false,
      value: () => this.vars.HighScoreList,
      x: 329,
      y: 151,
      width: 326,
      height: 252
    });
  }

  *whenIReceiveGameMute() {
    if (this.toString(this.vars.gameMute) === "true") {
      this.audioEffects.volume = 0;
    } else {
      this.audioEffects.volume = 100;
    }
  }

  *whenGreenFlagClicked() {
    this.audioEffects.volume = 100;
    this.vars.gameMode = "normal";
    this.broadcast("Menu");
  }

  *whenIReceiveMenu() {
    this.vars.flapSpeed = 0.1;
    this.vars.pipeNew = "true";
    this.vars.gamePause = "false";
    this.vars.birdPlay = "false";
    this.vars.birdFlap = "ture";
    this.vars.userSethighscore = "false";
    this.vars.encodeUsername = "false";
    this.vars.userEarnmedal = 0;
    this.vars.userScore = 0;
    this.vars.birdGravity = 0;
    if (this.toString(this.vars.gameMode) === "impossible") {
      this.vars.gameScrollx = -7;
    } else {
      this.vars.gameScrollx = -3.5;
    }
  }

  *whenIReceiveMenu2() {
    yield* this.startSound("sfx_swooshing");
  }

  *whenIReceiveStart() {
    yield* this.startSound("sfx_swooshing");
  }

  *whenIReceiveShowRate() {
    yield* this.startSound("sfx_swooshing");
  }

  *whenIReceiveHideRate() {
    yield* this.startSound("sfx_swooshing");
  }

  *whenIReceiveTap() {
    this.vars.birdPlay = "true";
  }

  *whenIReceiveGameOver() {
    this.vars.gameScrollx = 0;
  }

  *whenIReceiveShowHighscores() {
    yield* this.startSound("sfx_swooshing");
  }

  *whenIReceiveHideHighscores() {
    yield* this.startSound("sfx_swooshing");
  }

  *whenIReceiveShowSettings() {
    yield* this.startSound("sfx_swooshing");
  }

  *whenIReceiveHideSettings() {
    yield* this.startSound("sfx_swooshing");
  }

  *whenIReceiveGameOver2() {
    yield* this.wait(0.8);
    yield* this.playSoundUntilDone("sfx_swooshing");
    yield* this.startSound("sfx_swooshing");
  }
}
